//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerShortName { get; set; }
        public string CustomerDescription { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<bool> IsOften { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public string LabelId { get; set; }
        public string FactoryId { get; set; }
        public byte[] ERPDate { get; set; }
        public string ERPID { get; set; }
    }
}
