//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FtpFile
    {
        public string FtpFileId { get; set; }
        public string FtpFileName { get; set; }
        public string FtpDirectory { get; set; }
        public string FtpFileDescription { get; set; }
        public Nullable<long> FtpFileSize { get; set; }
        public string PluginCommand { get; set; }
        public string UploadUser { get; set; }
        public string UploadComputer { get; set; }
        public string PKId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
