//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        public string LotId { get; set; }
        public string LotSN { get; set; }
        public string ProductId { get; set; }
        public string LotStatus { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> OriginalQty { get; set; }
        public string PriorityLevel { get; set; }
        public string UOMId { get; set; }
        public string ShiftId { get; set; }
        public string WorkcenterId { get; set; }
        public string ResourceId { get; set; }
        public string VendorId { get; set; }
        public string VendorLotSN { get; set; }
        public string CustomerId { get; set; }
        public string CustomerLotSN { get; set; }
        public string BoxId { get; set; }
        public string MOId { get; set; }
        public string MOItemId { get; set; }
        public string MOItemTaskId { get; set; }
        public string CellId { get; set; }
        public string WorkflowId { get; set; }
        public string WorkflowStepId { get; set; }
        public string SubWorkflowStepId { get; set; }
        public string SpecificationId { get; set; }
        public Nullable<bool> IsMoveIn { get; set; }
        public string NextWorkflowStepId { get; set; }
        public string PreviousWorkflowStepId { get; set; }
        public string LatestTxnCode { get; set; }
        public string LatestUserId { get; set; }
        public Nullable<System.DateTime> LatestMoveDate { get; set; }
        public Nullable<System.DateTime> LatestActivityDate { get; set; }
        public string ParentLotId { get; set; }
        public string ParentLotSNList { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string AcceptOnDeviationStatus { get; set; }
        public string QCComment { get; set; }
        public string QCResult { get; set; }
        public string BatchId { get; set; }
        public string BoxSN { get; set; }
        public string CarrierId { get; set; }
        public string CarrierSN { get; set; }
        public Nullable<System.DateTime> CarrierCreateTime { get; set; }
        public Nullable<System.DateTime> InventoryInDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string LatestDataChainId { get; set; }
        public string Color { get; set; }
        public string SendQCReportId1 { get; set; }
    }
}
