//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q_issue_Rec_ForCustomer
    {
        public string Q_issue_Rec_ForCustomerId { get; set; }
        public string Q_issueRecName { get; set; }
        public string CustomerId { get; set; }
        public string ProductID { get; set; }
        public string OrderName { get; set; }
        public string MachineNo { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        public string IssueTypeId { get; set; }
        public string IssueDesc { get; set; }
        public string Image4ID { get; set; }
        public string Image3ID { get; set; }
        public string Image2ID { get; set; }
        public string Image1ID { get; set; }
        public string ImageID { get; set; }
        public string UserName { get; set; }
        public string VentureName { get; set; }
        public string VentureID { get; set; }
        public string Action { get; set; }
        public Nullable<int> StockQty { get; set; }
        public string UserId { get; set; }
        public string ResponWorkable { get; set; }
        public string IsAction { get; set; }
        public string IsTraining { get; set; }
        public string EffectValidation { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Model { get; set; }
        public string ProblemCompletion { get; set; }
        public string Reason { get; set; }
        public string WorkflowStepId { get; set; }
        public string WorkflowStatus { get; set; }
        public string ImageUserName { get; set; }
    }
}
