//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO
    {
        public string SOId { get; set; }
        public string SOName { get; set; }
        public string SODescription { get; set; }
        public string SOType { get; set; }
        public string SOStates { get; set; }
        public string CustomerId { get; set; }
        public string FactoryId { get; set; }
        public string DeliveryFactoryId { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public byte[] ERPDATE { get; set; }
        public string ERPID { get; set; }
        public string SAP_AUART { get; set; }
        public string SAP_WAERK { get; set; }
        public string SAP_VKORG { get; set; }
        public string SAP_VTWEG { get; set; }
        public string SAP_VKGRP { get; set; }
        public Nullable<System.DateTime> SAP_VDATU { get; set; }
        public string SAP_KUNNR { get; set; }
        public string SAP_NAMEALL { get; set; }
        public string SAP_ADRNR { get; set; }
        public string SAP_TELF1 { get; set; }
        public Nullable<System.DateTime> SAP_EDATU { get; set; }
    }
}
