//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ter_Customer_Com_Records
    {
        public string Ter_Customer_Com_RecordsId { get; set; }
        public string MOName { get; set; }
        public Nullable<int> SerialNumber { get; set; }
        public string CustomerId { get; set; }
        public string Model { get; set; }
        public string MachineNo { get; set; }
        public string FactoryNo { get; set; }
        public Nullable<System.DateTime> UsingDate { get; set; }
        public Nullable<System.DateTime> ComplaintTime { get; set; }
        public string ComplaintContent { get; set; }
        public string ImageID { get; set; }
        public string IssueTypeID { get; set; }
        public string Protocol { get; set; }
        public string SpareParts { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> SpareCost { get; set; }
        public string VentureID { get; set; }
        public string InvoiceNo { get; set; }
        public string IsAfterSale { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContact { get; set; }
        public string ReturnsAndSingleNo { get; set; }
        public string FaultIdentification { get; set; }
        public string ActionReport { get; set; }
        public string Accountability { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageID1 { get; set; }
        public string ImageID2 { get; set; }
        public string CustomerName { get; set; }
        public string VentureName { get; set; }
        public string DefectType { get; set; }
        public string ProblemCompletion { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string Reason { get; set; }
        public string WorkflowStepId { get; set; }
        public string WorkflowStatus { get; set; }
        public string IsTraining { get; set; }
        public string ImageUserName { get; set; }
    }
}
