//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXSaleAfterWorkNote
    {
        public int ID { get; set; }
        public string WorkContent { get; set; }
        public string SameProductCheck { get; set; }
        public string EnemyProductCheck { get; set; }
        public string HandlingSituation { get; set; }
        public Nullable<int> MainID { get; set; }
    }
}
