//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXSaleAfterMain
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerPhone { get; set; }
        public string ServiceReason { get; set; }
        public string ProblemType { get; set; }
        public string ProblemDescription { get; set; }
        public string Filename { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string IsFinish { get; set; }
        public string ProductName { get; set; }
        public string ProductID { get; set; }
        public string LotName { get; set; }
        public string MoID { get; set; }
        public string IsXJR { get; set; }
    }
}
