//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSaleAfterApp.Models.OrbitModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXSaleAfterAssessment
    {
        public int ID { get; set; }
        public string SaleAfterAssessment { get; set; }
        public string IsInTime { get; set; }
        public string WorkingAbility { get; set; }
        public string Is_Train { get; set; }
        public string IsDone { get; set; }
        public string IsChek { get; set; }
        public string Suggest { get; set; }
        public Nullable<int> MainID { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
    }
}
